name: C/C++ develop CI

on:
  push:
    branches: 
      - develop
      - 'MNO-**'
  pull_request:
    branches: 
    - develop
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.7

    - name: Install Dependecies
      run: |
        sudo apt-get -yqq install unzip git
        python -m pip install --upgrade pip
        pip install flake8 pytest scons
    
    - name: Install ARM  ToolChains
      run: |
        wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/arm-2017q2-v6/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2
        sudo tar xjf gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2 -C /opt
        /opt/gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-gcc --version

    - name: Install STM32CubeIDE
      uses: xanderhendriks/action-build-stm32cubeide@v7.0 
      
      with:
        project-path : 'component/firmware/STM32H7B0/Template'
        project-target : 'Template'
    - name: Building STM32H7B0
      with:
        project-path : 'component/firmware/STM32H7B0/Template'
        project-target : 'core'
    - name: Building STM32F411
      with:
        project-path : 'component/firmware/STM32F411/Template'
        project-target : 'Template'
        
    - run: ls
    - run: ls
#    - name: make
#      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
